Repository BIT-Studio-4/GTS, pull requests merged in 2024-09, with the labels that each got.

#110 6 make popups elegant
  Assets/Scripts/HUDManager.cs
  Assets/Scripts/PlaceObject.cs
Labels: enhancement

#115 Make customers walk by store
  Assets/Materials/Ground.mat
  Assets/Materials/Ground.mat.meta
  Assets/Materials/Path.mat
  Assets/Materials/Path.mat.meta
  Assets/Materials/Road.mat
  Assets/Materials/Road.mat.meta
  Assets/Prefabs/Bottle_01.prefab
  Assets/Prefabs/Can_01.prefab
  Assets/Prefabs/Customer.prefab
  Assets/Prefabs/Food_Box_01.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Customer.cs
  Assets/Scripts/CustomerManager.cs
  Assets/Scripts/InventoryManager.cs
  Assets/Scripts/RandomSell.cs
  Assets/Scripts/RandomSell.cs.meta
  Assets/Scripts/SellItem.cs
  Assets/Scripts/SellItem.cs.meta
  Assets/Scripts/StockManager.cs
  Assets/Scripts/StockManager.cs.meta
Labels: enhancement

#119 Fix structure softlocking
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/StoreManager.cs
Labels: bug

#118 Update API on User info change
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.orig
  Assets/Scripts/API/HTTPRequests.cs
  Assets/Scripts/API/Types/User.cs
  Assets/Scripts/API/Types/UserLogin.cs
  Assets/Scripts/API/Types/UserLogin.cs.meta
  Assets/Scripts/ApiManager.cs
  Assets/Scripts/ApiManager.cs.meta
  Assets/Scripts/GameManager.cs
Labels: enhancement

#132 Added automatic builds to hotfix branch
  .github/workflows/main.yml
Labels: ci

#137 Update Total Cost colour when money is updated
  Assets/Scripts/StoreManager.cs
Labels: bug

#145 Deploy Sprint 7
  .github/workflows/main.yml
  Assets/InputSystem_Actions.inputactions
  Assets/Materials/Floor.mat
  Assets/Materials/Floor.mat.meta
  Assets/Prefabs/Bottle_01.prefab
  Assets/Prefabs/Can_01.prefab
  Assets/Prefabs/Food_Box_01.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Shelf_01.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.orig
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GhostObjectPlacement.cs
  Assets/Scripts/HUDManager.cs
  Assets/Scripts/InventoryManager.cs
  Assets/Scripts/InventoryManager.cs.meta
  Assets/Scripts/PauseMenu.cs
  Assets/Scripts/PauseMenu.cs.meta
  Assets/Scripts/PlaceObject.cs
  Assets/Scripts/PlaceableObject.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/SellItem.cs
  Assets/Scripts/StockManager.cs
  Assets/Scripts/StoreManager.cs
  Assets/Scripts/UIManager.cs
  Assets/UI/hud.uss
  Assets/UI/hud.uxml
  ProjectSettings/ProjectSettings.asset
Labels: branch merge
