Repository BIT-Studio-4/GTS, pull requests merged in 2024-07, with the labels that each got.

#38 Create object prefabs
  Assets/Prefabs/Bottle_01.prefab
  Assets/Prefabs/Bottle_01.prefab.meta
  Assets/Prefabs/Can_01.prefab
  Assets/Prefabs/Can_01.prefab.meta
  Assets/Prefabs/Food_Box_01.prefab
  Assets/Prefabs/Food_Box_01.prefab.meta
  Assets/Prefabs/Shelf_01.prefab
  Assets/Prefabs/Shelf_01.prefab.meta
Labels: enhancement

#34 Complete interaction system
  Assets/Scripts/InteractableObject.cs
  Assets/Scripts/PlayerInteraction.cs
Labels: enhancement

#44 Create random buying
  Assets/Scripts/RandomSell.cs
  Assets/Scripts/RandomSell.cs.meta
Labels: enhancement

#45 fix random selling
  Assets/Prefabs/Bottle_01.prefab
  Assets/Prefabs/Can_01.prefab
  Assets/Prefabs/Food_Box_01.prefab
Labels: bug

#40 Connect example user from API to Unity
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/API.meta
  Assets/Scripts/API/HTTPRequests.cs
  Assets/Scripts/API/HTTPRequests.cs.meta
  Assets/Scripts/API/Types.meta
  Assets/Scripts/API/Types/Data.cs
  Assets/Scripts/API/Types/Data.cs.meta
  Assets/Scripts/API/Types/User.cs
  Assets/Scripts/API/Types/User.cs.meta
  Assets/Scripts/GameManager.cs
Labels: enhancement, API
