Repository BIT-Studio-4/GTS, pull requests merged in 2024-08, with the labels that each got.

#65 Make items only placeable on shelves
  Assets/Prefabs/Shelf_01.prefab
  Assets/Scripts/PlaceObject.cs
  ProjectSettings/TagManager.asset
Labels: enhancement

#64 Create hud
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/HUDManager.cs
  Assets/Scripts/HUDManager.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/UI Toolkit.meta
  Assets/UI Toolkit/UnityThemes.meta
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss.meta
  Assets/UI.meta
  Assets/UI/hud.uss
  Assets/UI/hud.uss.meta
  Assets/UI/hud.uxml
  Assets/UI/hud.uxml.meta
  Assets/UI/main-panel.asset
  Assets/UI/main-panel.asset.meta
  Assets/UnityDefaultRuntimeTheme.tss
  Assets/UnityDefaultRuntimeTheme.tss.meta
Labels: enhancement

#91 Automatic build making on push
  .github/workflows/main.yml
Labels: ci

#93 Created ghost object
  Assets/3D Models/Bottle_01.fbx.meta
  Assets/3D Models/Can_01.fbx.meta
  Assets/3D Models/Food_Box_01.fbx.meta
  Assets/3D Models/Shelf_01.fbx.meta
  Assets/Animation.meta
  Assets/Animation/Ghost Object Invalid.anim
  Assets/Animation/Ghost Object Invalid.anim.meta
  Assets/Animation/Ghost Object Pulse.anim
  Assets/Animation/Ghost Object Pulse.anim.meta
  Assets/Animation/Ghost Object.controller
  Assets/Animation/Ghost Object.controller.meta
  Assets/Materials/Bottle Lid.mat
  Assets/Materials/Bottle Lid.mat.meta
  Assets/Materials/Bottle.mat
  Assets/Materials/Bottle.mat.meta
  Assets/Materials/Box.mat
  Assets/Materials/Box.mat.meta
  Assets/Materials/Can Label.mat
  Assets/Materials/Can Label.mat.meta
  Assets/Materials/Can Lid.mat
  Assets/Materials/Can Lid.mat.meta
  Assets/Materials/Ghost Object Material.mat
  Assets/Materials/Ghost Object Material.mat.meta
  Assets/Materials/Shelf Railing.mat
  Assets/Materials/Shelf Railing.mat.meta
  Assets/Materials/Shelf.mat
  Assets/Materials/Shelf.mat.meta
  Assets/Prefabs/Bottle_01.prefab
  Assets/Prefabs/Can_01.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/GhostObjectPlacement.cs
  Assets/Scripts/GhostObjectPlacement.cs.meta
  Assets/Scripts/InventoryManager.cs
  Assets/Scripts/PlaceObject.cs
  Assets/Scripts/PlaceableObject.cs
  Assets/Scripts/PlayerInteraction.cs
  Assets/Sprites/Materials.meta
  Assets/Sprites/Materials/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.mat
  Assets/Sprites/Materials/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.mat.meta
  Assets/Sprites/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.jpg
  Assets/Sprites/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.jpg.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: enhancement

#103 Deploy Sprint 5
  .github/workflows/main.yml
  Assets/3D Models/Bottle_01.fbx.meta
  Assets/3D Models/Can_01.fbx.meta
  Assets/3D Models/Food_Box_01.fbx.meta
  Assets/3D Models/Shelf_01.fbx.meta
  Assets/Animation.meta
  Assets/Animation/Ghost Object Invalid.anim
  Assets/Animation/Ghost Object Invalid.anim.meta
  Assets/Animation/Ghost Object Pulse.anim
  Assets/Animation/Ghost Object Pulse.anim.meta
  Assets/Animation/Ghost Object.controller
  Assets/Animation/Ghost Object.controller.meta
  Assets/Materials/Bottle Lid.mat
  Assets/Materials/Bottle Lid.mat.meta
  Assets/Materials/Bottle.mat
  Assets/Materials/Bottle.mat.meta
  Assets/Materials/Box.mat
  Assets/Materials/Box.mat.meta
  Assets/Materials/Can Label.mat
  Assets/Materials/Can Label.mat.meta
  Assets/Materials/Can Lid.mat
  Assets/Materials/Can Lid.mat.meta
  Assets/Materials/Ghost Object Material.mat
  Assets/Materials/Ghost Object Material.mat.meta
  Assets/Materials/Shelf Railing.mat
  Assets/Materials/Shelf Railing.mat.meta
  Assets/Materials/Shelf.mat
  Assets/Materials/Shelf.mat.meta
  Assets/Prefabs/Bottle_01.prefab
  Assets/Prefabs/Can_01.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/UI/InventoryGridItem.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GhostObjectPlacement.cs
  Assets/Scripts/GhostObjectPlacement.cs.meta
  Assets/Scripts/HUDManager.cs
  Assets/Scripts/InventoryItemSlot.cs
  Assets/Scripts/InventoryManager.cs
  Assets/Scripts/InventoryManager.cs.orig
  Assets/Scripts/PlaceObject.cs
  Assets/Scripts/PlaceableObject.cs
  Assets/Scripts/PlayerInteraction.cs
  Assets/Scripts/StoreItemSO.cs
  Assets/Scripts/StoreItemSlot.cs
  Assets/Scripts/StoreManager.cs
  Assets/Scripts/UIManager.cs
  Assets/Sprites/Materials.meta
  Assets/Sprites/Materials/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.mat
  Assets/Sprites/Materials/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.mat.meta
  Assets/Sprites/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.jpg
  Assets/Sprites/kawaii-cute-ghost-clipart-doodle-element-happy-halloween-ghost-cartoon-illustration-halloween-party-card-invitation-print-shirt-or-product-print-sticker-design-vector.jpg.meta
  Assets/UI/hud.uss
  Assets/UI/hud.uxml
  README.md
Labels: branch merge
